### ISSUE TITLE
[BUG]: Failed to render <PayPalHostedFieldsProvider /> component.

### ISSUE THREAD

**Issue by mariana-berkii** [paypal/paypal-js#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

When the Hosted Fields component rerenders due to state changes, an error appears:
_Failed to render <PayPalHostedFieldsProvider /> component. BraintreeError: Element already contains a Braintree iframe._
As I understand this happens because the PayPalHostedFieldsProvider component has been initiated and when rerender happens, the PayPalHostedFieldsProvider component doesn't check if the hosted fields instance exists, it just tries to render the card fields again, which throws an error.

### 😕 Current Behavior

On rerenderings Hosted Fields fail with the error:
```
react-paypal-js.js:1237 Uncaught Error: Failed to render <PayPalHostedFieldsProvider /> component. BraintreeError: Element already contains a Braintree iframe.
    at react-paypal-js.js:1237:15
    at basicStateReducer (react-dom.development.js:16540:41)
    at updateReducer (react-dom.development.js:16664:22)
    at updateState (react-dom.development.js:17004:10)
    at Object.useState (react-dom.development.js:17915:16)
    at useState (react.development.js:1622:21)
    at PayPalHostedFieldsProvider (react-paypal-js.js:1188:20)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19588:20)
    at beginWork (react-dom.development.js:21601:16)
```

### 🤔 Expected Behavior

When the checkout page rerenders due to state changes (e.g. changes to basket), it would be good if in such cases the PayPal Hosted Fields component would not try to render Hosted Fields once again, but use the existing instance.

### 🌍 Environment

```markdown
| Software         |            Version(s)           |
| ---------------- | ------------------------------- |
| react-paypal-js  |              8.1.3              |
| Browser          |   Google Chrome 124.0.6367.60   |
| Operating System |   Windows 10 Enterprise 64-bit  |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GinkTran** [comment]
Any update on this error?
We're showing a component to render Paypal component with condition.
It works fine only once, the second times it always throws this error
```
react-paypal-js.js:1237 Uncaught Error: Failed to render <PayPalHostedFieldsProvider /> component. BraintreeError: Element already contains a Braintree iframe.
```

**Comment by dylan-berndt** [comment]
bump

**Comment by davidmclark** [comment]
Any update? This bug surfaced when upgrading Next.js from v12 to v13 or later. 

It appears to occur only in when running development mode where Next.js renders the component twice in succession. This makes the component totally unusable in a non-production environment.

```
react-paypal-js.js:1262 Uncaught Error: Failed to render <PayPalHostedFieldsProvider /> component. BraintreeError: Element already contains a Braintree iframe.
```

**Comment by sonya-invoicesimple** [comment]
+1. We experience this bug for last 6 months after bumping nextjs from 13.* to 14+ - Debugging attempts brought us to the same conclusion as @davidmclark arrived at.

We have an SDK wrapper around `@paypal/react-paypal-js` and launching it in pure react works flawlessly unlike nextjs.

## React
![image](https://github.com/user-attachments/assets/cb02027d-6cc7-4b2f-85b9-d58a20de221e)
## Next.js 14.2.18
![image](https://github.com/user-attachments/assets/f7096be6-9a46-4b4d-bd94-9e964a42a73d)


we have tried both 8.1.1 and  8.7.0 versions of sdk and no luck. 

I hope there will be an update on this one in the near future 🙏
